# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coords.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63oords.proto\x12\x06\x63oords\" \n\x0c\x43oordRequest\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\"0\n\rCoordResponse\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x32L\n\x0c\x43oordService\x12<\n\tGetCoords\x12\x14.coords.CoordRequest\x1a\x15.coords.CoordResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coords_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COORDREQUEST._serialized_start=24
  _COORDREQUEST._serialized_end=56
  _COORDRESPONSE._serialized_start=58
  _COORDRESPONSE._serialized_end=106
  _COORDSERVICE._serialized_start=108
  _COORDSERVICE._serialized_end=184
# @@protoc_insertion_point(module_scope)
